language: node_js

cache:
  directories:
    - '$HOME/.npm'

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - '9'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm i -g npm

install:
  - npm ci

after_success:
  - npm run build
  - npm run semantic-release
